"use strict";
console.log("Area of the rectangle:");
var length = 5;
var width = 7;
console.log("Area :",length*width);
console.log("Area of cirlce:");
var radius = 6;
console.log("Area of ○:",radius*radius*3.141);
var side = 8;
console.log("Area of cube:",side*side*6);
var fahrenheit_temp = 80;
console.log("Fahrenheit to celsius:",5/9*(fahrenheit_temp-32));
var part = 6000;
var total = 10000;
console.log("Percentage:",(part/total)*100);
var seconds = 420;
console.log("second to minutes:",seconds/60);
var minutes = 255;
console.log("minutes to seconds",minutes*60);
console.log("Answer of Q:1 is 'b=6'");
console.log("Answer of Q:2 is 'y=7'");
console.log("Answer of Q:3 is 'y=14'");
console.log("Answer of Q:4 is 'n=27'");
console.log("Answer of Q:5 is 'result=8'");
console.log("Answer of Q:6 is 'm=2 n=4 p=10'");
console.log("Answer of Q:7 is 'a=6 b=2 c=2 d=6'");
console.log("Answer of Q:8 is 'm=3 o=3 n=2 result=5'");